indir: ../../../Task2_image_inpainting/lama/output  # to be overriden in CLI
outdir: ../../../Task2_image_inpainting/lama/output  # to be overriden in CLI

model:
  path: ../../../Task2_image_inpainting/lama/biglama/biglama  # to be overriden in CLI
  checkpoint: best.ckpt

dataset:
  kind: default
  img_suffix: .png
  pad_out_to_modulo: 8

device: cpu
out_key: inpainted
